agenda/urls.py
from django.urls import path
from . import views

app_name = 'agenda'

urlpatterns = [
    path('', views.Principal.as_view(), name="principal"),
    path('atualizacliente', views.Atualiza_Cliente.as_view(), name="atualizacliente"),
    path('atualizajson', views.Atualiza_Json.as_view(), name="atualizajson"),
    path('atualizaevento', views.Atualiza_Evento.as_view(), name="atualizaevento"),
    path('marcar', views.Marcar.as_view(), name="marcar"),
    path('tabela', views.Tabela.as_view(), name="tabela"),
    path('mensagens', views.Mensagens.as_view(), name="mensagens"),
    path('atualizasms', views.Atualiza_Sms.as_view(), name="atualizasms"),
    path('configuracao', views.ConfiguracaoView.as_view(), name="configuracao"),
]

agendamento/urls.py
from django.contrib import admin
from django.urls import path, include   
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('agenda.urls')),
    path('perfil/',include('perfil.urls')),
    path('pedido/',include('pedido.urls')),
    path('admin/', admin.site.urls),
    path('produto/', include('produto.urls')),
] 

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Criar.as_view(), name="criar"),
    path('concluido/', views.Cadastro_concluido.as_view(), name="cadastro_concluido"),
    path('atualizar/', views.Atualizar.as_view(), name="atualizar"),
    path('login/', views.Login.as_view(), name="login"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('password-reset/', views.Password_Reset.as_view(), name="password_reset"),
    path('code-verification/', views.Code_Verification.as_view(), name="code_verification"),
    path('reset-password/', views.Reset_password.as_view(), name='reset_password'),
    path('reset-password/<uidb64>/<token>/', views.Reset_password.as_view(), name='password_reset_confirm'),
    path('lista-desejos/', views.ListaDesejoProduto.as_view(), name="lista_desejos"),
    path('novo-cadastro/', views.NovoCadastro.as_view(), name="novo_cadastro"),
    path('save-subscription/', views.SaveSubscription.as_view(), name="save_subscription")
]

perfil/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models


class PerfilForm(forms.ModelForm):
     
    def __init__(self, perfil=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.perfil = perfil
    
    class Meta:
        model = models.PerfilUsuario
        fields = ('nome_completo','cep', 'endereco', 'numero', 'complemento', 
                  'bairro', 'cidade', 'estado', 'telefone')


class PerfilComEnderecoForm(PerfilForm):

    complemento = forms.CharField(
        widget=forms.TextInput(),
        label='Complemento',
        required=False,
        help_text='Esse campo não é obrigatório'
    )

    bairro = forms.CharField(
        widget=forms.TextInput(),
        label='Bairro',
        required=False,
        help_text='Esse campo não é obrigatório'
    )

    cep = forms.CharField(
        widget=forms.TextInput(),
        label='CEP'
    )
    
    
class PerfilSemEnderecoForm(PerfilForm):

    class Meta:
        model = models.PerfilUsuario
        fields = ('nome_completo', 'telefone')
    

class UserForm(forms.ModelForm):
    
    password = forms.CharField(
        required=False,
        widget=forms.PasswordInput(),
        label='Senha',
        help_text='Use uma letra maiuscula e um numero'
    )
    password2 = forms.CharField(
        required=False,
        widget=forms.PasswordInput(),
        label='Confirmação de senha',
        help_text='Digite a senha igual a senha informada no campo acima'
    )

    email = forms.CharField(
        required=True,
        widget=forms.TextInput(),
        label='Email',
        help_text='Enviaremos a confirmação de cadastro e outros emails para esse endereço'
    )

    def __init__(self, usuario=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.usuario = usuario        
        
    class Meta:
        model = User
        fields = ('email','password', 'password2')
    
    def clean(self, *args, **kwargs):
        data = self.data
        cleaned = self.cleaned_data
        validation_error_msgs = {}
        
        first_name = data.get('first_name')
        last_name =  data.get('last_name')
        usuario_data = data.get('username')
        password_data = data.get('password')
        password2_data = data.get('password2')
        email_data = cleaned.get('email')
        
        usuario_db = User.objects.filter(username=usuario_data).first()
        email_db = User.objects.filter(email=email_data).first()
        
        error_msg_user_exists = 'Usuário já existe'
        error_msg_email_exists = 'Email já existe'
        error_msg_password_empty = 'Senha precisa ser informada'
        error_msg_firstname_empty = 'Primeiro nome precisa ser informado'
        error_msg_password_match = 'As duas senhas não conferem'
        error_msg_password_short = 'A senha precisa de pelo menos 6 caracteres'
        
        if self.usuario:
            
            if password_data:
                if password_data != password2_data:
                    validation_error_msgs['password'] = error_msg_password_match
                    validation_error_msgs['password2'] = error_msg_password_match
                if len(password_data) < 6:
                    validation_error_msgs['password'] = error_msg_password_match
        else:
            if email_db:
                if email_data == email_db.email:                
                    validation_error_msgs['email'] = error_msg_email_exists
            
            if usuario_db:
                validation_error_msgs['username'] = error_msg_user_exists
           
            if not password_data:
                validation_error_msgs['password'] = error_msg_password_empty            
            
            if not password2_data:
                validation_error_msgs['password2'] = error_msg_password_empty            
        
        if validation_error_msgs:
            raise (forms.ValidationError(validation_error_msgs))

perfil/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views.generic import ListView
from django.views import View
from datetime import datetime
from . import forms
from .models import PerfilUsuario, PasswordResetCode, ListaDesejoProduto as ListaDesejo, PushSubscription
from produto.models import Produto
from produto.produto_service import ProdutoService
from .perfil_service import PerfilService
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm
from django.contrib.auth.tokens import default_token_generator
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.decorators.csrf import csrf_exempt
import copy
import json
import random
import string    


class BasePerfil(View):
    
    template_name = 'perfil/criar.html'
    
    def setup(self, *args, **kwargs):
        
        super().setup(*args, **kwargs)
        
        self.carrinho = copy.deepcopy(self.request.session.get('carrinho'), {})
        self.perfil = None

        if self.request.user.is_authenticated:
            self.perfil = PerfilUsuario.objects.filter(usuario=self.request.user).first()
            self.usuario = User.objects.filter(username=self.request.user).first()

            perfilForm = forms.PerfilSemEnderecoForm(
                                data=self.request.POST or None,
                                instance=self.perfil, 
                                perfil=self.perfil) 
        
            self.context = {
                'userform': forms.UserForm(
                                    data=self.request.POST or None, 
                                    usuario=self.request.user,
                                    instance=self.request.user,    
                            ),
                'perfilform': perfilForm,
                'pagina_cadastro': True 
            }
        else:            
            
            perfil_form = forms.PerfilSemEnderecoForm(data=self.request.POST or None)    
            
            self.context = {
                'userform': forms.UserForm(data=self.request.POST or None),
                'perfilform': perfil_form,
                'pagina_cadastro': True,
                'novo_cadastro': True
            }
            
        self.userform = self.context['userform']
        self.perfilform = self.context['perfilform']
                
        self.renderizar = render(self.request, self.template_name, self.context)
    
    def get(self, *args, **kwargs):        
        return self.renderizar


class Criar(BasePerfil):
    
    def post(self, *args, **kwargs):
        
        if not self.userform.is_valid() or not self.perfilform.is_valid():    
            msg = 'Há erros no formulário, por favor verifique nos campos abaixo'  
            messages.error(self.request, msg)             
            return self.renderizar

        password = self.userform.cleaned_data.get('password')
        email = self.userform.data.get('email')
        nome_completo = self.perfilform.cleaned_data.get('nome_completo')
        nomes = nome_completo.split(' ')
        first_name = nomes[0]
        tamanho_lista = len(nomes)
        last_name = nomes[tamanho_lista - 1]
        perfil_endereco = self.request.POST.get('perfil_endereco')

        username = str(email).split('@')[0]

        if self.request.user.is_authenticated:
            usuario = get_object_or_404(User, username=self.request.user.username)
            
            usuario.username = username
            if password:
                usuario.set_password(password)           
            usuario.email = email 
            usuario.first_name = first_name
            usuario.last_name = last_name
            usuario.save(force_update=True)
            
            if not self.perfil:
                self.perfilform.cleaned_data['usuario'] = usuario
                perfil = PerfilUsuario(**self.perfilform.cleaned_data)
                perfil.perfil_endereco = perfil_endereco
                perfil.save()
            else:
                perfil = self.perfilform.save(commit=False)
                perfil.usuario = usuario
                perfil.save(force_update=True)
        else:
            usuario = self.userform.save(commit=False)
            usuario.username = username
            usuario.email = email 
            usuario.first_name = first_name
            usuario.last_name = last_name
            usuario.set_password(password)
            usuario.save()
            
            perfil = self.perfilform.save(commit=False)
            perfil.usuario = usuario
            perfil.save()
        
            if password:
                authentica = authenticate(
                    self.request,
                    username=username,
                    password=password
                )
                if authentica:
                    login(self.request, user=usuario)
        
        self.request.session['carrinho'] = self.carrinho
        self.request.session.save()      
        self.request.session['subscricao_notificacao'] = True
        msg = 'Seu cadastro foi realizado com sucesso'  
        messages.success(self.request, msg)        

        if self.request.session.get('url_destino') is not None:
            return redirect(self.request.session['url_destino'])

        return redirect('agenda:marcar')
           

class Cadastro_concluido(View):
    model = PerfilUsuario
    context_object_name = 'perfil'
    template_name = 'perfil/cadastro_concluido.html'
    paginate_by = 3

    def get(self, *args, **kwargs):
        usuario = self.request.user
        perfil = PerfilUsuario.objects.filter(usuario=usuario).get() 
        contexto = {
            'usuario': usuario,
            'perfil' : perfil
        }  
        
        return render(self.request, self.template_name, contexto)


class Atualizar(Criar):

    template_name = 'perfil/atualizar.html'
    
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:login')

        url = self.request.GET.get('url')
        self.request.session['url_destino'] = url   
        
        return self.renderizar    


class Login(View):
    
    def render_cacheless(self, action, path, context):
        response = render(action, path, context)
        response["Cache-Control"] = "no-cache, no-store, must-revalidate"
        response["Pragma"] = "no-cache"
        response["Expires"] = "0"
        
        return response

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            if self.request.user.is_staff:
                return redirect('agenda:principal')
            return redirect('agenda:marcar')

        #if 'HTTP_CACHE_CONTROL' in self.request.META and 'no-cache' in self.request.META['HTTP_CACHE_CONTROL']:
        url = self.request.GET.get('url')
        self.request.session['url_destino'] = url
        
        render_return = self.render_cacheless(self.request, 'perfil/login.html', {})
        
        return render_return

    def post(self, *args, **kwargs):
        username = self.request.POST.get('username')
        password = self.request.POST.get('password')
        
        if not username or not password:
            messages.error( 
                self.request,
                'Usuário ou senha inválidos'
            )
            return redirect('perfil:login')
        
        if PerfilService().validar_email(username):
            username = str(username).split('@')[0]
        
        if username.isdigit():
            telefone = username
            username = PerfilUsuario.objects.get(telefone=telefone).usuario.username
        
        usuario = authenticate(self.request, username=username, password=password)
        
        if not usuario:
            messages.error(
                self.request,
                "Usuário ou senha inválidos"
            )
            return redirect('perfil:login')
        
        login(self.request, user=usuario)

        if self.request.user.is_staff: 
            return redirect('agenda:principal')     
        
        return redirect('agenda:marcar')


class Logout(View):

    def get(self, *args, **kwargs):        
        logout(self.request)
        self.request.session.save()
        return redirect('perfil:login')


class Password_Reset(View):

    def get(self, *args, **kwargs):
        form = form = PasswordResetForm()        
        return render(self.request, 'perfil/password_reset.html', {'form': form, 'mensagem': ''})
    
    def post(self, *args, **kwargs):
        form = PasswordResetForm(self.request.POST)
        return PerfilService().password_reset(form=form,request=self.request)
   

class Code_Verification(View):

    def get(self, *args, **kwargs):        
        return render(self.request, 'perfil/code_validation.html')  

    def post(self, *args, **kwargs):
        codigo = self.request.POST.get('codigo')
        uidb64 = self.request.session.get('uidb64')
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
        if user is not None:
            password_reset_code = PasswordResetCode.objects.get(codigo=codigo)
            
            if default_token_generator.check_token(user, password_reset_code.token):
                return redirect('perfil:reset_password') 
            else:
                messages.error(
                    self.request,
                    'Token inválido ou o tempo de expiração está vencido'
                )

perfil/templates/perfil/atualizar.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block conteudo %}

{% load static %}

<script src="{% static 'assets/custom/js/form_userperfil.js' %} "></script>

<div class="row">
    
    <div class="col-lg mt-3">
        {% block titulocadastro %}
            <h4>Alteração dos dados no cadastro</h4>
            <p>Caso precise atualizar alguma informação do seu cadastro, utilize o formulário abaixo</p>
        {% endblock %}

        <form method="POST" action="{% url 'perfil:criar' %}">            
            {% csrf_token %}   
            {{perfilform|crispy}}       
            {{userform|crispy}}
            <input type="hidden" name="uf" id="uf" value="{{perfilform.data.estado}}">
            <div class="row">
                <div class="col">
                    <button type="submit" id="enviar_form_perfil"
                        class="btn btn-primary btn-lg btn-cadastro-perfil">
                        Enviar
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

perfil/templates/perfil/cadastro_concluido.html
{% extends 'base.html' %}

{% load omfilters %}

{% block conteudo %}

<div class="row mb-5">
    <div class="col-lg">
        <h2>Cadastro efetuado com sucesso</h2>

        <p class="lead">Um email foi enviado para você ativar seu cadastro</p>
        <p>Caso precise editar, <a href="{% url 'perfil:criar' %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Nome:</dt>
            <dd class="col-lg-4">{{usuario.first_name}}</dd>
            <dt class="col-lg-2">Sobrenome:</dt>
            <dd class="col-lg-4">{{usuario.last_name}}</dd>

            <dt class="col-lg-2">Idade:</dt>
            <dd class="col-lg-4">{{perfil.idade}}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{perfil.data_nascimento|formata_br_date}}</dd>

            <dt class="col-lg-2">CPF:</dt>
            <dd class="col-lg-4">{{perfil.cpf}}</dd>
            <dt class="col-lg-2">E-mail:</dt>
            <dd class="col-lg-4">{{usuario.email}}</dd>
        </dl>

        <p class="lead">Dados de endereço</p>
        <dl class="row">
            <dt class="col-lg-2">Endereço:</dt>
            <dd class="col-lg-4">{{perfil.endereco}}</dd>
            <dt class="col-lg-2">Número:</dt>
            <dd class="col-lg-4">{{perfil.numero}}</dd>

            <dt class="col-lg-2">Complemento:</dt>
            <dd class="col-lg-4">{{perfil.complemento|none_to_blank}}</dd>
            <dt class="col-lg-2">Bairro:</dt>
            <dd class="col-lg-4">{{perfil.bairro|none_to_blank}}</dd>

            <dt class="col-lg-2">Cidade:</dt>
            <dd class="col-lg-4">{{perfil.cidade}}</dd>
            <dt class="col-lg-2">Estado:</dt>
            <dd class="col-lg-4">{{perfil.estado}}</dd>

            <dt class="col-lg-2">CEP:</dt>
            <dd class="col-lg-4">{{perfil.cep}}</dd>
        </dl>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="card-columns">

            {% for produto in produtos %}   
            
            <div class="card">
                {% if produto.imagem %}
                  <a href="{{produto.slug}}">  
                    <img class="card-img-top" src="{{ produto.imagem.url }}" alt="Card image cap">
                  </a>
                {% endif %} 

                <div class="card-body">
                    <h5 class="card-title">{{ produto.nome }}</h5>
                    <p class="card-text">{{ produto.descricao }}</p>
                    <div class="container product-price-block text-center">
                        {% if produto.preco_marketing_promocional > 0 %}
                            <span class="product-price">
                                {{ produto.preco_marketing_promocional|formata_preco }}
                            </span>
                        {% endif %}
                            <span class="product-old-price text-muted">
                                {{ produto.preco_marketing|formata_preco }}
                            </span>
                    </div>
                </div>
                <div class="card-footer bg-transparent border-top-light-custom text-center">
                    <a href="{{produto.slug}}" class="btn btn-primary btn-sm m-1 btn-block">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        Comprar
                    </a>
                </div>
            </div>
            {% endfor  %}

        </div>
    </div>
</div>

<div class="row mt-3">
    <div class="col">
        {% include 'parciais/_pagination.html' %}
    </div>
</div>


{% endblock %}

perfil/templates/perfil/code_validation.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block conteudo %}

<div class="container d-flex justify-content-center align-items-center vh-100"> 

    {% if not request.user.is_authenticated %}
    <div class="card borderless">
        <h3>Alteração de senha</h3>
        <p class="mt-4">Digite o código que foi enviado para seu email:</p>

        <div class="card-body">
            <form method="POST" action="{% url 'perfil:code_verification' %}">
                {% csrf_token %}
                <input type="hidden" id="uidb64" name="uidb64" value="{{uidb64}}">
                <input type="hidden" id="token" name="token" value="{{token}}">
                <div class="form-group">
                    <input type="text" name="codigo" id="codigo" placeholder="Código para ativação"
                           class="form-control codigo-validacao" aria-describedby="usuarioHelp">
                </div>
                <button type="submit" id="btn_login_perfil" class="btn btn-primary btn-block btn-lg btn_login">
                    Validar
                </button>  
           
            </form>  
        </div>
    </div>
{% endif %}

</div>
{% endblock %} 

perfil/templates/perfil/criar.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block conteudo %}

{% load static %}

<script src="{% static 'assets/custom/js/form_userperfil.js' %} "></script>

<div class="row ml-5">
    
    <div class="col-lg mt-3">
        {% block titulocadastro %}
            <h4>Cadastro</h4>
            <p>Utilize o formulário abaixo para realizar seu cadastro</p>
        {% endblock %}

        <form method="POST" action="">            
            {% csrf_token %}          
            {{perfilform|crispy}}
            {{userform|crispy}}
            <input type="hidden" name="uf" id="uf" value="{{perfilform.data.estado}}">
            <div class="row">
                <div class="col">
                    <button type="submit" id="enviar_form_perfil"
                        class="btn btn-primary btn-lg btn-cadastro-perfil">
                        Enviar
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

perfil/templates/perfil/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block conteudo %}

<div class="container d-flex justify-content-center align-items-center vh-100"> 

    {% if not request.user.is_authenticated %}
    <div class="card borderless">
        <h3>Login</h3>
        <p class="mt-4">Se já fez o cadastro, basta entrar com seu usuário e senha abaixo:</p>

        <div class="card-body">
            <form method="POST" action="{% url 'perfil:login' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="InputUsuario">Email ou nome de usuário</label>
                    <input type="text" name="username" id="username" placeholder="Digite seu usuário"
                           class="form-control" aria-describedby="usuarioHelp">
                </div>
                <div class="form-group">
                    <label for="InputUsuario">Senha</label>
                    <input type="password" name="password" placeholder="Digite sua senha"
                           class="form-control" id="id_password">
                </div>
                <input type="checkbox" class="form-check-inline mb-2" name="lembrarme" id="lembrarme" /> 
                Lembrar-me
                <span id="capslock" style="display:none">
                    <i class="fa-regular fa-keyboard far ml-4" style="color: #c85f5f;"></i>
                    Caps Lock ligado
                </span>
                <button type="submit" id="btn_login_perfil" class="btn btn-primary btn-block btn-lg btn_login">
                    Entrar
                </button>  
           </div>
        </form>  
        <div class="card-body">
            <a href="{% url 'perfil:password_reset' %}" class="btn btn-primary btn-block btn-lg btn_login">
                Esqueci minha senha
            </a>     
        </div>
        <div class="card-body">
            <a href="{% url 'perfil:criar' %}?perfil_endereco=false" class="btn btn-primary btn-block btn-lg btn_login">
                Cadastrar
            </a>
        </div>

    </div>
{% endif %}

</div>

<script>
    $(document).ready(function() {
    // Verifica se o nome de usuário está armazenado
    var username = localStorage.getItem('username');
    if (username) {
        $('#username').val(username);
        $('#lembrarme').prop('checked', true);
    }

    // Evento para armazenar ou remover o nome de usuário
    $('#lembrarme').change(function() {
        if ($(this).is(':checked')) {
            localStorage.setItem('username', $('#username').val());
        } else {
            localStorage.removeItem('username');
        }
    });
});

window.addEventListener("keydown", function(event) {
    if (event.getModifierState("CapsLock")) {
        $("#capslock").show();
    } else {
        $("#capslock").hide();
    }
});
</script>

{% endblock %}

perfil/templates/perfil/password_reset.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block conteudo %}

<div class="container d-flex justify-content-center align-items-center vh-100"> 

    {% if not request.user.is_authenticated %}
    <div class="card borderless">
        <h3>Recuperação de senha</h3>
        <p class="mt-4">Digite seu email e um código será enviado para validar a solicitação e acessar formulário para recadastrar uma nova senha:</p>

        <div class="card-body">
            <form method="POST" action="{% url 'perfil:password_reset' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="text" name="email" id="email" placeholder="Digite seu email"
                           class="form-control" aria-describedby="usuarioHelp">
                </div>
                <button type="submit" id="btn_login_perfil" class="btn btn-primary btn-block btn-lg btn_login">
                    Enviar
                </button>  
           
            </form>  
        </div>
    </div>
{% endif %}

</div>
{% endblock %} 

perfil/templates/perfil/reset_password.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block conteudo %}

<div class="container d-flex justify-content-center align-items-center vh-100"> 

    {% if not request.user.is_authenticated %}
    <div class="card borderless">
        <h3>Cadastro de nova senha</h3>
        <p class="mt-4">Digite sua nova senha 2 vezes e clique em recadastrar para concluir:</p>

        <div class="card-body">
            <form method="POST" action="{% url 'perfil:reset_password' %}">
                {% csrf_token %}

                {{error}}

                <input type="hidden" id="uidb64" name="uidb64" value="{{uidb64}}">

                {{form|crispy}}
        
                <button type="submit" id="btn_login_perfil" class="btn btn-primary btn-block btn-lg btn_login">
                    Recadastrar
                </button> 

            </form>  
        </div>
    </div>
{% endif %}

</div>
{% endblock %} 

<script>
    $(function(){
        $("#id_new_password1").focus();
    })();
</script>