agenda/urls.py
from django.urls import path
from . import views

app_name = 'agenda'

urlpatterns = [
    path('', views.Principal.as_view(), name="principal"),
    path('atualizacliente', views.Atualiza_Cliente.as_view(), name="atualizacliente"),
    path('atualizajson', views.Atualiza_Json.as_view(), name="atualizajson"),
    path('atualizaevento', views.Atualiza_Evento.as_view(), name="atualizaevento"),
    path('marcar', views.Marcar.as_view(), name="marcar"),
    path('tabela', views.Tabela.as_view(), name="tabela"),
    path('mensagens', views.Mensagens.as_view(), name="mensagens"),
    path('atualizasms', views.Atualiza_Sms.as_view(), name="atualizasms"),
    path('configuracao', views.ConfiguracaoView.as_view(), name="configuracao"),
]

agendamento/urls.py
from django.contrib import admin
from django.urls import path, include   
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('agenda.urls')),
    path('perfil/',include('perfil.urls')),
    path('pedido/',include('pedido.urls')),
    path('admin/', admin.site.urls),
    path('produto/', include('produto.urls')),
] 

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Criar.as_view(), name="criar"),
    path('concluido/', views.Cadastro_concluido.as_view(), name="cadastro_concluido"),
    path('atualizar/', views.Atualizar.as_view(), name="atualizar"),
    path('login/', views.Login.as_view(), name="login"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('password-reset/', views.Password_Reset.as_view(), name="password_reset"),
    path('code-verification/', views.Code_Verification.as_view(), name="code_verification"),
    path('reset-password/', views.Reset_password.as_view(), name='reset_password'),
    path('reset-password/<uidb64>/<token>/', views.Reset_password.as_view(), name='password_reset_confirm'),
    path('lista-desejos/', views.ListaDesejoProduto.as_view(), name="lista_desejos"),
    path('novo-cadastro/', views.NovoCadastro.as_view(), name="novo_cadastro"),
    path('save-subscription/', views.SaveSubscription.as_view(), name="save_subscription")
]

produto/urls.py
from django.urls import path
from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name="lista"),
    path('<slug>', views.DetalheProduto.as_view(), name="detalhe"),
    path('adicionaraocarrinho/', views.AdicionarCarrinho.as_view(), name="adicionaraocarrinho"),
    path('removerdocarrinho/', views.RemoverCarrinho.as_view(), name="removerdocarrinho"),
    path('carrinho/', views.Carrinho.as_view(), name="carrinho"),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name="resumodacompra"),
    path('tabela/', views.Tabela.as_view(), name="tabela"),
    path('variacoes/', views.Variacoes_json.as_view(), name="variacoes"),
    path('busca/', views.Busca.as_view(), name="busca"),
    path('entrada/', views.EntradaProduto.as_view(), name="entrada")
]

perfil/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models


class PerfilForm(forms.ModelForm):
     
    def __init__(self, perfil=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.perfil = perfil
    
    class Meta:
        model = models.PerfilUsuario
        fields = ('nome_completo','cep', 'endereco', 'numero', 'complemento', 
                  'bairro', 'cidade', 'estado', 'telefone')


class PerfilComEnderecoForm(PerfilForm):

    complemento = forms.CharField(
        widget=forms.TextInput(),
        label='Complemento',
        required=False,
        help_text='Esse campo não é obrigatório'
    )

    bairro = forms.CharField(
        widget=forms.TextInput(),
        label='Bairro',
        required=False,
        help_text='Esse campo não é obrigatório'
    )

    cep = forms.CharField(
        widget=forms.TextInput(),
        label='CEP'
    )
    
    
class PerfilSemEnderecoForm(PerfilForm):

    class Meta:
        model = models.PerfilUsuario
        fields = ('nome_completo', 'telefone')
    

class UserForm(forms.ModelForm):
    
    password = forms.CharField(
        required=False,
        widget=forms.PasswordInput(),
        label='Senha',
        help_text='Use uma letra maiuscula e um numero'
    )
    password2 = forms.CharField(
        required=False,
        widget=forms.PasswordInput(),
        label='Confirmação de senha',
        help_text='Digite a senha igual a senha informada no campo acima'
    )

    email = forms.CharField(
        required=True,
        widget=forms.TextInput(),
        label='Email',
        help_text='Enviaremos a confirmação de cadastro e outros emails para esse endereço'
    )

    def __init__(self, usuario=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.usuario = usuario        
        
    class Meta:
        model = User
        fields = ('email','password', 'password2')
    
    def clean(self, *args, **kwargs):
        data = self.data
        cleaned = self.cleaned_data
        validation_error_msgs = {}
        
        first_name = data.get('first_name')
        last_name =  data.get('last_name')
        usuario_data = data.get('username')
        password_data = data.get('password')
        password2_data = data.get('password2')
        email_data = cleaned.get('email')
        
        usuario_db = User.objects.filter(username=usuario_data).first()
        email_db = User.objects.filter(email=email_data).first()
        
        error_msg_user_exists = 'Usuário já existe'
        error_msg_email_exists = 'Email já existe'
        error_msg_password_empty = 'Senha precisa ser informada'
        error_msg_firstname_empty = 'Primeiro nome precisa ser informado'
        error_msg_password_match = 'As duas senhas não conferem'
        error_msg_password_short = 'A senha precisa de pelo menos 6 caracteres'
        
        if self.usuario:
            
            if password_data:
                if password_data != password2_data:
                    validation_error_msgs['password'] = error_msg_password_match
                    validation_error_msgs['password2'] = error_msg_password_match
                if len(password_data) < 6:
                    validation_error_msgs['password'] = error_msg_password_match
        else:
            if email_db:
                if email_data == email_db.email:                
                    validation_error_msgs['email'] = error_msg_email_exists
            
            if usuario_db:
                validation_error_msgs['username'] = error_msg_user_exists
           
            if not password_data:
                validation_error_msgs['password'] = error_msg_password_empty            
            
            if not password2_data:
                validation_error_msgs['password2'] = error_msg_password_empty            
        
        if validation_error_msgs:
            raise (forms.ValidationError(validation_error_msgs))

templates/parciais/_carrinho.html
{% load static %}

{% load omfilters %}

<div class="table-responsive">
    <table class="table">
        <thead>
            <th style="width: 15%">Imagem</th>
            <th style="width: 40%">Nome e variação</th>
            <th></th>
            <th>Quantidade</th>
            <th>Total</th>
            <th>Remover</th>
        </thead>
        <tbody>
        {% for item in carrinho.values %}
            <tr>
                <td class="d-none d-lg-block">
                    {% if item.imagem %}
                        <img class="cart-img" src={% get_media_prefix %}{{item.imagem|remove_aspas}}>
                    {% endif %}    
                </td>
                <td>
                    <a href="{% url 'produto:detalhe' item.slug %}">
                      {{ item.produto_nome }} - {{ item.variacao_nome }}
                    </a>
                <td>                       
                <td>{{ item.quantidade }}</td>                        
                <td>
                    {% if item.preco_quantitativo_promocional %}
                        R$  {{ item.preco_quantitativo_promocional }}
                    {% else %}
                        R$  {{ item.preco_quantitativo }}
                    {% endif %}    
                </td> 
                <td>
                    <a class="ml-3" href="{% url 'produto:removerdocarrinho' %}?vid={{item.variacao_id}}">
                        <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>    

    </table>
</div>

templates/parciais/_footer.html
{% load static %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

<script src="{% static 'assets/bootstrap/js/popper.min.js' %} "></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %} "></script>
<script defer src="{% static 'assets/font-awesome/js/all.js' %} "></script>
<script src="{% static 'assets/custom/js/scripts.js' %} "></script>


{% if pagina_cadastro %}

<script src="{% static 'assets/custom/js/password_strength.js' %} "></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.pt-BR.min.js"></script>

<script>
    
    $(document).ready(function(){

        $("#id_data_nascimento").datepicker({
            format: "dd/mm/yyyy",
            language: "pt-BR"
        });

        $("#id_cep").mask("00000-000");
        $("id_data_nascimento").mask("00/00/0000");
        $("#id_cpf").mask("000.000.000-00");

        $("#id_password").passwordStrengthIndicator();
        $("#id_password2").passwordStrengthIndicator();
        
    });  
</script>
{% endif %}


{% if subscricao_notificacao %}
    <script src="{% static 'assets/custom/js/user_notification.js' %} "></script>    
{% endif %}    

<script src="https://code.jquery.com/ui/1.14.1/jquery-ui.js"></script>
<script>

    var calendarInstance1 = new calendarJs( "calendar1", 
                                            __TRANSLATION_OPTIONS, { 
                                            showExtraTitleBarButton : false    
                                        });

    //defaultEventDuration: duracao do evento                                    
    calendarInstance1.setOptions( {
        views: {
                fullMonth: {
                    maximumEventsPerDayDisplay: 5
                }
            },  
        defaultEventDuration: 35,    
        allowHtmlInDisplay: true,
        visibleDays: [ 0, 1, 2, 3, 4, 5 ],
        useLocalStorageForEvents: false,
        showExtraTitleBarButton: false,
        exportEventsEnabled: true,
    });
        
    objEventos = []
    if($("#agendamentos").val() != undefined){
        agendamentos = JSON.parse($("#agendamentos").val());    
        if(agendamentos != undefined || agendamentos.length != 0){
            agendamentos.forEach(agendamento => {
                json_evento_agendamento = agendamento.fields.json_evento;
                json_evento_agendamento = json_evento_agendamento.replaceAll("\\", "");
                json_evento_agendamento = JSON.parse(json_evento_agendamento);
                
                calendarInstance1.addEvent(json_evento_agendamento, !1, !1, !1);
            });
            calendarInstance1.turnOnFullScreen();    
        } 
    }
        
</script>

templates/parciais/_fretes.html
{% load static %}

{% load omfilters %}

<div class="table-responsive">
    <table class="table" id="table_fretes">
        <thead>
            <th style="width: 15%"></th>
            <th style="width: 40%">Transportadora</th>
            <th></th>
            <th>Preço</th>
            <th class="text-center">Tempo de envio:</th>
        </thead>
        <tbody>
        {% for frete in fretes %}
            {% if frete.price %}
                <tr>
                    <td class="d-none d-lg-block">
                        {% if frete.company.picture %}
                            <img class="cart-img" src={{frete.company.picture|remove_aspas}}>
                        {% endif %}    
                    </td>
                    <td>{{frete.name}} <td>                       
                    <td>{{frete.price|formata_preco}}</td>                        
                    <td class="text-center">{{frete.delivery_time}} dias</td> 
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>  
    </table>
</div>

<script>
    $(document).ready(function(){
       
       $.noConflict();

       $("#total_compra").html($("#total_carrinho").text().trim());

       $('#table_fretes tbody tr').click(
         function(){
            $('.selected').removeClass('selected');
            $(this).addClass('selected');
            let total_compra = calcula_total_geral(this);
            $("#total_compra").html(formata_preco(total_compra));
         }
       );

       function formata_strval_conv_float(strval){
            return strval.replace('R$ ', '').replace(',','.');
       }

       function formata_preco(numero){
           return numero.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
       }

       function calcula_total_geral(row){
            
            const celula_valor = $(row).children('td')[3];
            const valor_selecionado = parseFloat(formata_strval_conv_float(celula_valor.textContent)); 
            
            const str_total_carrinho = $("#total_carrinho").text().trim().replace('R$ ', '');
            const total_carrinho = parseFloat(str_total_carrinho);
            
            return valor_selecionado + total_carrinho;
       }
    });   
</script>
<script src="{% static 'assets/bootstrap/js/jquery-3.2.1.slim.min.js' %} "></script>

templates/parciais/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css'%}">
<link rel="stylesheet" href="{% static 'assets/custom/css/style.css'%}">

<link rel="stylesheet" href="https://code.jquery.com/ui/1.14.1/themes/base/jquery-ui.css">

<link rel="stylesheet" href="https://cdn.datatables.net/2.0.8/css/dataTables.dataTables.css" />

<link rel="stylesheet" href="https://cdn.datatables.net/colreorder/2.0.3/css/colReorder.dataTables.min.css" />

<link rel="stylesheet" href="https://cdn.datatables.net/keytable/2.12.1/css/keyTable.dataTables.min.css">

<link rel="stylesheet" href="https://cdn.datatables.net/buttons/3.0.2/css/buttons.dataTables.min.css">

<link rel="stylesheet" type="text/css" href="{% static 'assets/calendarjs/css/calendar.js.css'%}">

<script src="{% static 'assets/calendarjs/js/calendar.js'%}"></script>

<script src="{% static 'assets/calendarjs/js/calendar.translations.pt.js'%}"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

<script src="https://cdn.datatables.net/2.0.8/js/dataTables.js"></script>

<script src="https://cdn.datatables.net/colreorder/2.0.3/js/dataTables.colReorder.min.js"></script>

<script src="https://cdn.datatables.net/keytable/2.12.1/js/dataTables.keyTable.min.js"></script>

<script src="https://cdn.datatables.net/buttons/3.0.2/js/dataTables.buttons.min.js"></script>

<script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.colVis.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>

<script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.html5.min.js"></script>

<script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.print.min.js"></script>


<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.css" rel="stylesheet"/>

<script src="https://code.jquery.com/ui/1.14.1/jquery-ui.js"></script>

<script src"{% static 'assets/custom/js/dialogs.js' %}""></script>

templates/parciais/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/parciais/_nav.html
{% load omfilters %}

<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
    <a class="navbar-brand" href="/">Agendamento Pro</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
                {% if request.user.is_staff %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" id="navbarRelatorio" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">             
                                Sistema    
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">                    
                            <a class="dropdown-item" href="{% url 'agenda:principal' %}">
                                Agendador de atendimentos    
                            </a>
                            <a class="dropdown-item" href="{% url 'agenda:tabela' %}">
                                Listagem de atendimentos    
                            </a>

                            <a class="dropdown-item" href="{% url 'agenda:marcar' %}">
                                Marcar atendimento    
                            </a>
                        </div>
                    </li>
                    <form class="form-inline my-2 my-lg-0" action="{% url 'produto:busca' %}">
                        <input class="form-control mr-sm-2" type="search" placeholder="o que procura?" aria-label="Search" name="termo">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Buscar</button>
                    </form>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'agenda:marcar' %}"
                           style="color:#fff">
                           Marcar atendimento
                        </a>
                    </li>
                {% endif %}
            {% endif %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% if request.user.is_authenticated %}
                        {{request.user}}
                    {% else %}
                        Conta
                    {% endif %}    
                </a>
                <div class="dropdown-menu itemmenu_direita_esquerda" aria-labelledby="navbarDropdown">
                    
                    {% if request.user.is_authenticated %} 
                        <a class="dropdown-item" href="{% url 'perfil:atualizar' %}">
                            Ver ou alterar seu cadastro    
                        </a>   
                        {% if request.user.is_superuser %}
                            <a class="dropdown-item" href="{% url 'agenda:configuracao' %}">
                                Configuração    
                            </a>
                        {% endif %}
                    {% else %}
                    <a class="dropdown-item" href="{% url 'perfil:login' %}">
                        Entrar na conta
                    </a>    
                    <a class="dropdown-item" href="{% url 'perfil:criar' %}">
                        Cadastrar nova conta
                    </a>    
                    {% endif %}    
                    
                    {% if request.user.is_authenticated %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'perfil:logout' %}">Sair</a>
                    {% endif %}
                </div>
            </li>
        </ul>

    </div>
</nav>

templates/parciais/_pagination.html
{% if is_paginated %}
<div class="pagination">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">&laquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
        </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}

        {% if page_obj.number == num %}
        <li class="page-item active">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}

        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
        </li>
        {% endif %}
    </ul>
</div>
{% endif %}

templates/parciais/_scripts_head.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

<script src="https://cdn.datatables.net/2.0.8/js/dataTables.js"></script>

<script src="https://cdn.datatables.net/colreorder/2.0.3/js/dataTables.colReorder.min.js"></script>

<script src="https://cdn.datatables.net/keytable/2.12.1/js/dataTables.keyTable.min.js"></script>

<script src="https://cdn.datatables.net/buttons/3.0.2/js/dataTables.buttons.min.js"></script>

<script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.colVis.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>

<script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.html5.min.js"></script>

<script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.print.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.pt-BR.min.js"></script>

<script>
    $(document).ready(function(){
        $("#id_data_nascimento").datepicker({
            format: "dd/mm/yyyy",
            language: "pt-BR"
        });
    });
</script>

templates/parciais/_tabela_pessoa.html
<script>
    $(document).ready(function(){
        
        $.noConflict();

        const table = $('#table_id').DataTable({
            colReorder: true,
            keys: true,
        });

        $('#table_id').css('width', '100%');

        $(".dt-layout-cell").first().hide();
        $("#dt-search-0").css('width','80%');
        $(".card-body").css('padding','0.75rem');

        id_perfil = null;
        nomeperfil_selecionado=null;
        table.on('click', 'td', function (e) {
            row = $(this).parent('tr');
            id_perfil = row.attr('perfil_id');
            nomeperfil_selecionado = row.children('td.nome_perfil').html();
            emailperfil_selecionado = row.children('td.email_perfil').html();

        });
        

        function atualizaPessoa(){
            $.ajaxSetup({
                headers:
                { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') }
            });

            strJsonEvent = localStorage.getItem('strJsonEvent');
            jsonNewEvent = JSON.parse(strJsonEvent);
            id_novo_evento = jsonNewEvent[0].pk;

            let jsonIdDiv = JSON.parse(jsonNewEvent[0].fields.json_evento);
            let divNovoEvento = $('div[event-id="'+jsonIdDiv.id+'"]');
            tipoServico = "corte de cabelo"; 
            titulo_com_perfil = 'Serviço: ' + tipoServico + ' / ' + 'Nome: ' + nomeperfil_selecionado
            jsonIdDiv.title = titulo_com_perfil;
                                    
            //divNovoEvento.html(jsonIdDiv.title +jsonIdDiv.from);
            
            $.ajax({
                type: "POST",
                dataType: "json",
                url: "http://localhost:8000/atualizacliente",
                data: {
                    "perfil_id": id_perfil,
                    "evento_id": id_novo_evento,
                    "jsonEvent": jsonIdDiv,
                    "ultima_atualizacao" : ultima_atualizacao,
                    "csrfmiddlewaretoken": $('meta[name="csrf-token"]').attr('content')
                },
                success: function(jsonData) { 
                    localStorage.setItem('strJsonEvent', jsonData);
                    strJsonEvent = localStorage.getItem('strJsonEvent');
                }
            });

            $("#dialog").dialog("close");
        }
        
        table.on('dblclick', 'td', function (e) {
            atualizaPessoa();            
        });  

        $("#table_id").on('keypress',function(e) {
            if(e.which == 13) {
                atualizaPessoa();
            }
        });

} );  
</script>

<meta name="csrf-token" content="{{ csrf_token }}">

<div class="container vh-100"> 

    <div class="card borderless">
        <div class="card-body">
            <table id="table_id" class="display">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>email</th>
                
                    </tr>
                </thead>
                <tbody>
                    {% for perfil in perfis %}
                    <tr perfil_id="{{perfil.id}}">
                        <td class="nome_perfil">{{perfil.usuario.first_name}}</td>             
                        <td class="email_perfil">{{perfil.usuario.email}}</td>                       
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>        
    </div>
</div>