agenda/urls.py
from django.urls import path
from . import views

app_name = 'agenda'

urlpatterns = [
    path('', views.Principal.as_view(), name="principal"),
    path('atualizacliente', views.Atualiza_Cliente.as_view(), name="atualizacliente"),
    path('atualizajson', views.Atualiza_Json.as_view(), name="atualizajson"),
    path('atualizaevento', views.Atualiza_Evento.as_view(), name="atualizaevento"),
    path('marcar', views.Marcar.as_view(), name="marcar"),
    path('tabela', views.Tabela.as_view(), name="tabela"),
    path('mensagens', views.Mensagens.as_view(), name="mensagens"),
    path('atualizasms', views.Atualiza_Sms.as_view(), name="atualizasms"),
    path('configuracao', views.ConfiguracaoView.as_view(), name="configuracao"),
]

agendamento/urls.py
from django.contrib import admin
from django.urls import path, include   
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('agenda.urls')),
    path('perfil/',include('perfil.urls')),
    path('pedido/',include('pedido.urls')),
    path('admin/', admin.site.urls),
    path('produto/', include('produto.urls')),
] 

pedido/urls.py
from django.urls import path
from . import views

app_name = "pedido"

urlpatterns = [
   path('', views.Pagar.as_view(), name="pagar"),
   path('salvarpedido', views.SalvarPedido.as_view(), name="salvarpedido"),
   path('compraconcluida/', views.CompraConcluida.as_view(), name="compraconcluida"),   
   path('meuspedidos', views.MeusPedidos.as_view(), name="meuspedidos"),
   path('detalhe/<int:pk>', views.Detalhe.as_view(), name="detalhe"),
   path('tabela', views.Tabela.as_view(), name="tabela"),
   path('itens-pedido', views.ItensPedido_json.as_view(), name="itens_pedido"),
   path('atualizapedido/', views.Atualizar_Pedido.as_view(), name="atualizapedido"),
   path('desativar/', views.Desativar_Pedido.as_view(), name="desativar"),
]  

pedido/models.py
from datetime import date, datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from produto.models import Variacao, Produto

class Pedido(models.Model):
    
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    data_emissao = models.DateField(default=datetime.now().date())
    hora_emissao = models.TimeField(default=timezone.now().time())
    total = models.DecimalField(max_digits=10, decimal_places=2, null=False)
    qtd_total = models.FloatField(default=0)
    status = models.CharField(
        default='C',
        max_length=1,
        choices=(
            ('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Preparando'),
            ('E', 'Enviado'),
            ('F', 'Finalizado'),
        )
    )
    desativado = models.BooleanField(default=False)
    codigo_rastreio_correio = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return f'Pedido N. {self.pk}'


class ItemPedido(models.Model):
   
    pedido   = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto  = models.ForeignKey(Produto, on_delete=models.CASCADE)   
    variacao = models.ForeignKey(Variacao, on_delete=models.CASCADE) 
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    preco_promocional = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    quantidade = models.PositiveIntegerField()
    imagem = models.CharField(max_length=2000)

    def __str__(self):
        return f'Item do pedido N. {self.pedido}'

    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens do pedido'    

pedido/views.py
from django.shortcuts import render, redirect
from django.core import serializers
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.core.paginator import Paginator
from produto.models import Variacao, Produto, ProdutoSimples, SaidaProduto
from produto.produto_service import ProdutoService
from . import pedido_service 
from django.db import connection
from .models import Pedido, ItemPedido
from .email.py_email import PyEmail 
from datetime import datetime, date
from pprint import pprint

class DispachLoginRequired(View):
    
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect("perfil:criar")
    
        return super().dispatch(*args, **kwargs)
    
    def get_query_set(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(usuario=self.request.user)
        return qs


class Pagar(DispachLoginRequired, View):
    
  
    def get(self, *args, **kwargs):
        
        if not self.request.session.get('carrinho'):
            return redirect('produto:resumodacompra')
        
        carrinho = self.request.session.get('carrinho')
        carrinho_variacao_ids = [v for v in carrinho]
        bd_variacoes = list(
            Variacao.objects.filter(id__in=carrinho_variacao_ids)
        )
        
        return redirect('pedido:salvarpedido')


class SalvarPedido(View):    
    
    def get(self, *args, **kwargs):
        carrinho = self.request.session.get('carrinho')
        if carrinho is None:
            return redirect('pedido:compraconcluida') 
        
        carrinho_variacao_ids = [v for v in carrinho]
        bd_variacoes = list(
            Variacao.objects.select_related('produto').filter(id__in=carrinho_variacao_ids)
        )
        
        for variacao in bd_variacoes:
            vid = variacao.id
            svid = str(vid)
            estoque = variacao.estoque
            qtd_carrinho = int(carrinho[svid]['quantidade'])
            preco_unt = carrinho[svid]['preco_quantitativo']
            preco_unt_promo = carrinho[svid]['preco_quantitativo_promocional']
            
            if estoque < qtd_carrinho:
                carrinho[svid]['quantidade'] = estoque        
                carrinho[svid]['preco_quantitativo'] = estoque * preco_unt
                carrinho[svid]['preco_quantidade_promocional'] = estoque * preco_unt_promo    
                
                messages.error(
                    self.request,
                    'Estoque insuficiente para alguns produtos do seu carrinho. '
                    'Reduzimos a quantidade desses produtos. Por favor, verifique '
                    'em quais produtos foram afetados a seguir'
                )
                self.request.session.save()
                return redirect('produto:carrinho')       
        
        qtd_total_carrinho = sum([int(item['quantidade']) for item in carrinho.values()])
        valor_total_carrinho =  sum(
                                    [
                                        item.get('preco_quantitativo_promocional')
                                        if item.get('preco_quantitativo_promocional')
                                        else 
                                        item.get('preco_quantitativo')
                                        for item in carrinho.values()
                                    ]
                                ) 
        pedido = Pedido(usuario=self.request.user, 
                        total=valor_total_carrinho, 
                        qtd_total=qtd_total_carrinho,
                        status='C',
                        data_emissao=datetime.today(),
                        hora_emissao=datetime.now())   
        pedido.save()
        
         
        ItemPedido.objects.bulk_create([
            ItemPedido(
                pedido=pedido,
                produto=Produto.objects.filter(id=v['produto_id']).first(),
                produto_id=v['produto_id'],
                variacao=Variacao.objects.filter(id=v['variacao_id']).first(),
                preco=v['preco_quantitativo'],
                preco_promocional=v['preco_quantitativo_promocional'],
                quantidade=v['quantidade'],
                imagem=v['imagem']
            ) for v in carrinho.values()
        ])

        for v in carrinho.values():
            ProdutoService().salvar_saida_produto(variacao=Variacao.objects.filter(id=v['variacao_id']).first(),
                                                    preco_final=v['preco_quantitativo_promocional'],
                                                    quantidade=v['quantidade'],
                                                    user=self.request.user,
                                                    data=datetime.today(),
                                                    hora=datetime.now(),
                                                    pedido=pedido)
        
        del self.request.session['carrinho']
        ProdutoService().limpa_session_carrinho_user(self.request.user)
        self.request.session['pedido_id'] = pedido.id 
        return redirect('pedido:compraconcluida')        
        

class CompraConcluida(View):
    
    def get(self, *args, **kwargs):
        pedido_id =  self.request.session.get('pedido_id')   
        pedido = Pedido.objects.filter(id=pedido_id).first()
        produtos_mais_vendidos = ProdutoService().get_produtos_mais_vendidos()
        contexto = {                   
                    'pedido': pedido, 
                    'produtos_mais_vendidos': produtos_mais_vendidos
                   }       
        py_email = PyEmail(pedido.usuario.email)
        py_email.set_body(username=self.request.user, nro_pedido=pedido_id, request=self.request)
        py_email.enviar()
        return render(self.request, 'pedido/compraconcluida.html', contexto)
    
class MeusPedidos(DispachLoginRequired, ListView):  
    model = Pedido
    template_name = 'pedido/lista.html'
    paginate_by = 10
    ordering = ['-id']
    
    def get(self, *args, **kwargs):
        usuario = self.request.user
        pedidos = Pedido.objects.filter(usuario=usuario).order_by('id').reverse()
        produtos_mais_vendidos = ProdutoService().get_produtos_mais_vendidos()
        page = self.request.GET.get('page', 1)
        paginator = Paginator(pedidos, per_page=10)
        page_object = paginator.get_page(page)
        contexto = {
            'pedidos': pedidos,
            'produtos_mais_vendidos': produtos_mais_vendidos,
            "page_obj": page_object,
            "is_paginated": True
        }
        return render(self.request, self.template_name, contexto)

class Detalhe(DispachLoginRequired, DetailView):
    model = Pedido
    produtos_mais_vendidos = ProdutoService().get_produtos_mais_vendidos()
    context_object_name = 'pedido'
    template_name = 'pedido/detalhe.html'
    pk_url_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['produtos_mais_vendidos'] = self.produtos_mais_vendidos     
        return context

class Tabela(DispachLoginRequired, ListView):
    model = Pedido
    template_name = 'pedido/tabela.html'
    context_object_name = 'pedidos'
    ordering = ['-id']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['area_sem_produtos'] = True
        pedidos = context['pedidos']
        pedidos = Pedido.objects.filter(desativado=False).order_by('id').reverse()
        for pedido in pedidos:            
            #data_datetime = datetime.datetime.strptime(pedido.data_emissao, "%d/%m/%Y")
            #pedido.data_emissao = data_datetime
            perfil = pedido.usuario.perfilusuario
            pedido.perfil_data = perfil
            data_ultima_compra = pedido_service.Pedido_Service().get_data_ultimo_pedido(user=pedido.usuario)
            pedido.data_ultima_compra = data_ultima_compra
        context['pedidos'] = pedidos
        return context

class Atualizar_Pedido(DispachLoginRequired, View):
    
    def post(self, *args, **kwargs):
        pedido_id = self.request.POST.get('pedidoid')
        de = self.request.POST.get('get')
        para = self.request.POST.get('para')
        para = pedido_service.Pedido_Service().get_sigla_status(para)
        pedido = Pedido.objects.get(id=pedido_id)
        pedido.status = para
        pedido.save()
        return JsonResponse(para, safe=False)

class Desativar_Pedido(View):
    
    def post(self, *args, **kwargs):
        pedido_id = self.request.POST.get('pedidoid')
        pedido = pedido_service.Pedido_Service().desativar_pedido(pedidoid=pedido_id)
        json_data = pedido.desativado
        return JsonResponse(json_data, safe=False)


class ItensPedido_json(ListView):
    
    def get(self, *args, **kwargs):
        pedido_id = self.request.GET.get('pedidoid')
        produtos = pedido_service.Pedido_Service().getItemsProdutos(pedido_id=pedido_id)
        json_data = serializers.serialize('json', produtos)
        return JsonResponse(json_data, safe=False)

pedido/templates/pedido/compraconcluida.html
{% extends 'base.html' %}
{% load omfilters %}
{% load static %}
{% block conteudo %}

<div class="row">
    <div class="col">
        <h3>{{pedido}}</h3>
        <div class="row mt-4">
            <h5 class="col-lg-4">Sua compra foi feita com sucesso</h5>
            <p class="ml-3">Um email foi enviado para {{request.user.email}} com as informações dessa compra, se quiser acompanhar veja em &nbsp;
                <a href="{% url 'pedido:meuspedidos' %}">pedidos</a></p>     
        </div>
        <div class="row">
            <div class="col">
                <div class="col-lg-2 font-weight-bold divleft">Número do pedido</div>
                <div class="col-lg-4 divleft">{{pedido.id}}</div>
                <div class="col-lg-2 font-weight-bold divleft">Total</div>
                <div class="col-lg-4 divleft">{{pedido.total|formata_preco}}</div>
    
                <div class="col-lg-2 font-weight-bold divleft">Qtd. Itens:</div>
                <div class="col-lg-4 divleft">{{pedido.qtd_total}}</div>
                <div class="col-lg-2 font-weight-bold divleft">Status:</div>
                <div class="col-lg-4 divleft">{{pedido.get_status_display}}</div>
            </div>
        </div>  
        <div class="row mt-4">
            <div class="col">
                <h3>Produtos</h3>
            </div>
        </div>
        <div class="table-responsive mt-3">
            <table class="table">
                <tr>
                    <th class="d-nome d-lg-block">Imagem</th>
                    <th>Produto</th>
                    <th>Variação</th>
                   <!-- <th>Preço</th> -->
                    <th>Quantidade</th>
                    <th>Total</th>
                </tr>
                {% for item in pedido.itempedido_set.all %}
                <tr>
                    <td class="d-none d-lg-block"> 
                        <img class="cart-img" src="{% get_media_prefix %}{{item.imagem|remove_aspas}}">
                    </td>
                    <td>{{item.produto}}</td>
                    <td>{{item.variacao}}</td>
                  <!--  <td>{{item.preco}}</td> -->
                    <td>{{item.quantidade}}</td>
                    <td>
                        {% if item.preco_promocional %}
                        {{item.preco_promocional|formata_preco}}
                        {% else %}
                        {{item.preco|formata_preco}}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

pedido/templates/pedido/detalhe.html
{% extends 'base.html' %}
{% load omfilters %}
{% load static %}
{% block conteudo %}

<div class="row">
    <div class="col">
        <h3>{{pedido}}</h3>
        
        <div class="row mt-4">
            <div class="col-lg-2 font-weight-bold ">Número do pedido:</div>
            <div class="col-lg-4">{{pedido.id}}</div>
            <div class="col-lg-2 font-weight-bold">Total:</div>
            <div class="col-lg-4">{{pedido.total|formata_preco}}</div>

            <div class="col-lg-2 font-weight-bold">Qtd. Itens:</div>
            <div class="col-lg-4">{{pedido.qtd_total}}</div>
            <div class="col-lg-2 font-weight-bold">Status:</div>
            <div class="col-lg-4">{{pedido.get_status_display}}</div>
        </div>  
        <div class="row mt-4">
            <div class="col">
                <h3>Produtos</h3>
            </div>
        </div>
        <div class="table-responsive mt-3">
            <table class="table">
                <tr>
                    <th class="d-nome d-lg-block">Imagem</th>
                    <th>Produto</th>
                    <th>Variação</th>
                   <!-- <th>Preço</th> -->
                    <th>Quantidade</th>
                    <th>Total</th>
                </tr>
                {% for item in pedido.itempedido_set.all %}
                <tr>
                    <td class="d-none d-lg-block"> 
                        <img class="cart-img" src="{% get_media_prefix %}{{item.imagem|remove_aspas}}">
                    </td>
                    <td>{{item.produto}}</td>
                    <td>{{item.variacao}}</td>
                  <!--  <td>{{item.preco}}</td> -->
                    <td>{{item.quantidade}}</td>
                    <td>
                        {% if item.preco_promocional %}
                        {{item.preco_promocional|formata_preco}}
                        {% else %}
                        {{item.preco|formata_preco}}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

pedido/templates/pedido/lista.html
{% extends 'base.html' %}
{% load omfilters %}
{% block conteudo %}

<div class="row">
    <div class="col">
        <h3 class="mb-4">Pedidos de {{user}}</h3>
        <p>Abaixo todos os seus pedidos realizados na loja.</p>

        <div class="table-responsive">
            <table class="table table-striped">
                <tr>
                    <th scope="col" class="text-center">Pedido</th>
                    <th scope="col" class="text-center">Data de emissão</th>
                    <th scope="col" class="text-center">Qtd. Itens</th>
                    <th scope="col" class="text-center">Status</th>
                    <th scope="col" class="text-center">Total</th>
                    <th scope="col" class="text-center">Mais detalhes</th>
                </tr>
                {% for pedido in page_obj %}
                <tr>
                    <th scope="row">{{pedido}}</td>                  
                    <td class="text-center">{{pedido.data_emissao|date:"d/m/Y"}}</td>  
                    <td class="text-center">{{pedido.qtd_total}}</td>
                    <td class="text-center">{{pedido.get_status_display}}</td>
                    <td class="text-center">{{pedido.total|formata_preco}}</td>
                    <td class="text-center">
                        <a href="{% url 'pedido:detalhe' pedido.id %}">
                            Ver <i class="fas fa-search-plus ml-2"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>
</div>

{% include 'parciais/_pagination.html' %}

 {% endblock %} 

pedido/templates/pedido/tabela.html
{% extends 'base.html' %}

{% load omfilters %}

{% load static %}

{% block conteudo %}

<meta name="csrf-token" content="{{ csrf_token }}">

<h1 class="text-center">Listagem de pedidos</h1>

<br />

<table id="table_id" class="display">
    <thead>
        <tr>
            <th></th>
            <th class="text-center" style="width: 10%">Número</th>
            <th>Situação</th>
            <th>Data de emissão</th>
            <th>Usuário</th>
            <th>Quantidade</th>
            <th>Valor total</th>
        </tr>
    </thead>
    <tbody>
        {% for pedido in pedidos %}
        <tr data-endereco="{{pedido.perfil_data.endereco}},{{pedido.perfil_data.numero}}, {{pedido.perfil_data.bairro}}, {{pedido.perfil_data.cep}}"
            data-cidade="{{pedido.perfil_data.cidade}},{{pedido.perfil_data.estado}}"
            data-ultimacompra="{{pedido.data_ultima_compra}}"
            data-token="'{{csrf_token}}'">
            <td class="dt-control" id="{{pedido.id}}"></td> 
            <td class="text-center">{{pedido.id}}</td>
            <td class="text-center">{{pedido.status|get_status_extenso}}</td>
            <td>{{pedido.data_emissao|formata_br_date}}   às   {{pedido.hora_emissao|formata_br_hora}}</td>
            <td>{{pedido.usuario.email}}</td>
            <td style="width: 10%">{{pedido.qtd_total}}</td>
            <td>{{pedido.total|formata_preco}}</td>
        </tr>
        
        {% endfor %}
    </tbody>
</table>
<div id="dialog-confirm-status" class="hide" title="Alteração da situação do pedido">
    <p>
        <span class="ui-icon ui-icon-alert" 
            style="float:left; margin:12px 12px 20px 0;">
        </span>
        <span id="msg-de-para">Isso irá alterar o status do pedido. Você tem certeza?</span>
    </p>
</div>  
<div id="dialog-confirm-deactivate" class="hide" title="Desativação do pedido">
    <p>
        <span class="ui-icon ui-icon-alert" 
            style="float:left; margin:12px 12px 20px 0;">
        </span>
        Isso irá desativar o pedido e você não poderá usá-lo no sistema da loja . Você tem certeza?
    </p>
</div>  


<script>
    $(document).ready(function(){
        
        $.noConflict();

        const table = $('#table_id').DataTable({
            colReorder: true,
            keys: true,
            pageLength:20,
            layout: {
                topStart: {
                    buttons: ['print', 'excel', 'pdf', 'csv', 'colvis' ]
                }
            }
        });


        $('.buttons-colvis').children('span').html('Colunas');
        $('.dt-search').children('label').html('Procurar')
        var showing = $("#table_id_info").html()
        showing = showing.replace('Showing','Exibindo').replace('entries', 'registros')
                                             .replace('to','a')
                                             .replace('of','de');
        $("#table_id_info").html(showing);

        $(".dt-paging-button").on('click', function(){
            $("#table_id_info").html(showing);
        });

        table.on('requestChild.dt', function (e, row) {
            row.child(format(row.data())).show();
        });        

        table.on('click', 'td.dt-control', function (e) {
            
            let tr  = e.target.closest('tr');
            let row = table.row(tr);
            let id_pedido = $(this).attr("id")

            if (row.child.isShown()) {
                row.child.hide();
                $("#tabela_variacoes").remove();
                $(".titulo_h5").remove();
                $(".linha_detalhe").remove();
            }
            else {
                row.child(format(row.data(), id_pedido, $(tr).attr('data-endereco'), 
                                $(tr).attr('data-cidade'), $(tr).attr('data-ultimacompra'),
                                $(tr).attr('data-token'))).show();
                showTabelaItens(id_pedido);
            }
        }); 
        
    });

    function format(d, id_pedido,dados_endereco,dados_cidade,data_ultima_compra,token) {
        return (
            '<div class="row">' +
                '<div class="col" >' +
                '<dl>' +
                '<dt>Numero:</dt>' +
                '<dd>' +
                d[1] +
                '</dd>' +
                '<dt>Data e hora:</dt>' +
                '<dd>' +
                d[3] +
                '</dd>' +
                '<dt>Situação:</dt>' +
                '<dd id="status_'+ id_pedido +'">'+ d[2] +'</dd>' +
                '</dl>' +
                '</div>' +
                '<div class="col" style=""">' +
                    '<dl>' +
                    '<dt>Endereço:</dt>' +
                    '<dd>' +
                    dados_endereco +
                    '</dd>' +
                    '<dt>Cidade:</dt>' +
                    '<dd>' +
                    dados_cidade +
                    '</dd>' +
                    '<dt>Última compra:</dt>' +
                    '<dd>'+ data_ultima_compra +'</dd>' +
                    '</dl>' +
                '</div>' +    
                '<div class="col" style=""">' +
                '<button data-status="' + d[2] + '" data-token="' + token + '" class="btn btn-secondary btn-block btn-lg btnChangeStatus"' +
                                'onclick="showDialogModalStatus('+ id_pedido +',' + token + ')">' +
                'Mudar para ' + getNextStep(d[2]) + '</button>'+ 
                '<button class="btn btn-primary btn-block btn-lg">' +
                ' Ver detalhes do pedido </button>'+ 
                '<button class="btn btn-danger btn-block btn-lg btn-delete"' +
                ' onclick="showDialogModalDeactivate('+ id_pedido +')">' +    
                ' Desativar pedido </button>'+ 
            '</div>' +    
            '</br>'
        );
    }

    async function showTabelaItens(id){     
        
        itens = await getTabelaItens(id); 
          
        table = getTableFromDataArray(itens, id);
        $("#"+id).parent().after(table);   
    }

    async function getTabelaItens(id){        

        return $.ajax({
                    type: "GET",
                    dataType: "json",
                    url: "{% url 'pedido:itens_pedido' %}",
                    data: "pedidoid=" + id,
                    success: function(jsonData) { 
                        return jsonData;
                    }
                });
    }

    function getTableFromDataArray(dataText, id_pedido){
        const dataObj = JSON.parse(dataText);
        let title = ''
        let tableHeader =   '<tr class="linha_detalhe">'+
                            '<td colspan=\"7\">'+
                            '<table id=\"tabela_variacoes\" style=\"width:100%\">' +
                            '<thead>' +
                                '<tr>' +
                                    '<th style="width:35%">Nome do produto</th>'+
                                    '<th>Nome da Variação</th>'+
                                    '<th style="text-align:center">Estoque</th>'+
                                    '<th style="text-align:center">Quantidade</th>'+
                                    '<th style="text-align:center">Preço</th>'+
                                    '<th style="text-align:center">Preço promocional</th>'
                                '</tr>'+
                            '</thead>'; 
        let tableRows = '';
        dataObj.forEach(row => {
            tableRows  += '<tr>'+                       
                '<td>'+row.fields.nome_produto+'</td>'+    
                '<td>'+row.fields.nome_variacao+'</td>'+                         
                '<td style="text-align:center; width:10%">' + row.fields.estoque + '</td>'+
                '<td style="text-align:center; width:10%">' + row.fields.quantidade + '</td>'+
                '<td style="text-align:right; width:10%">' + formata_preco(row.fields.preco) + '</td>'+
                '<td style="text-align:right; width:15%">' + formata_preco(row.fields.preco_promocional)+'</td>' +
                '</tr>'; 
        });             
        return ( title +
                 tableHeader +
                    '<tbody>'+
                        tableRows +                           
                     '</tbody>'+
                 '</table>' +
                 '</td>' +
                 '</tr>' 
               );     
    }

    function formata_preco(numero)
    {
        if(numero != undefined)
            return numero.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
        return '';
    }

    function apenasNumeros(string) 
    {
        var numsStr = string.replace(/[^0-9]/g,'');
        return parseInt(numsStr);
    }

    function getNextStep(status){
        
        switch(status){
            case 'Aprovado': return 'Preparando';
            case 'Criado': return 'Aprovado';
            case 'Reprovado': return 'Criado';
            case 'Preparando': return 'Enviado';
            case 'Enviado': return 'Finalizado';
            case 'Finalizado': return 'Preparando';
        }
    }
    function getStatusNameExtenso(sigla){

        switch(sigla){
            case 'A': return 'Aprovado';
            case 'C': return 'Criado';
            case 'R': return 'Reprovado';
            case 'P': return 'Preparando';
            case 'E': return 'Enviado';
            case 'F': return 'Finalizado';
        }
    }
    
</script> 

{% endblock conteudo %}