agenda/urls.py
from django.urls import path
from . import views

app_name = 'agenda'

urlpatterns = [
    path('', views.Principal.as_view(), name="principal"),
    path('atualizacliente', views.Atualiza_Cliente.as_view(), name="atualizacliente"),
    path('atualizajson', views.Atualiza_Json.as_view(), name="atualizajson"),
    path('atualizaevento', views.Atualiza_Evento.as_view(), name="atualizaevento"),
    path('marcar', views.Marcar.as_view(), name="marcar"),
    path('tabela', views.Tabela.as_view(), name="tabela"),
    path('mensagens', views.Mensagens.as_view(), name="mensagens"),
    path('atualizasms', views.Atualiza_Sms.as_view(), name="atualizasms"),
    path('configuracao', views.ConfiguracaoView.as_view(), name="configuracao"),
]

agendamento/urls.py
from django.contrib import admin
from django.urls import path, include   
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('agenda.urls')),
    path('perfil/',include('perfil.urls')),
    path('pedido/',include('pedido.urls')),
    path('admin/', admin.site.urls),
    path('produto/', include('produto.urls')),
] 

pedido/urls.py
from django.urls import path
from . import views

app_name = "pedido"

urlpatterns = [
   path('', views.Pagar.as_view(), name="pagar"),
   path('salvarpedido', views.SalvarPedido.as_view(), name="salvarpedido"),
   path('compraconcluida/', views.CompraConcluida.as_view(), name="compraconcluida"),   
   path('meuspedidos', views.MeusPedidos.as_view(), name="meuspedidos"),
   path('detalhe/<int:pk>', views.Detalhe.as_view(), name="detalhe"),
   path('tabela', views.Tabela.as_view(), name="tabela"),
   path('itens-pedido', views.ItensPedido_json.as_view(), name="itens_pedido"),
   path('atualizapedido/', views.Atualizar_Pedido.as_view(), name="atualizapedido"),
   path('desativar/', views.Desativar_Pedido.as_view(), name="desativar"),
]  

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Criar.as_view(), name="criar"),
    path('concluido/', views.Cadastro_concluido.as_view(), name="cadastro_concluido"),
    path('atualizar/', views.Atualizar.as_view(), name="atualizar"),
    path('login/', views.Login.as_view(), name="login"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('password-reset/', views.Password_Reset.as_view(), name="password_reset"),
    path('code-verification/', views.Code_Verification.as_view(), name="code_verification"),
    path('reset-password/', views.Reset_password.as_view(), name='reset_password'),
    path('reset-password/<uidb64>/<token>/', views.Reset_password.as_view(), name='password_reset_confirm'),
    path('lista-desejos/', views.ListaDesejoProduto.as_view(), name="lista_desejos"),
    path('novo-cadastro/', views.NovoCadastro.as_view(), name="novo_cadastro"),
    path('save-subscription/', views.SaveSubscription.as_view(), name="save_subscription")
]

produto/urls.py
from django.urls import path
from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name="lista"),
    path('<slug>', views.DetalheProduto.as_view(), name="detalhe"),
    path('adicionaraocarrinho/', views.AdicionarCarrinho.as_view(), name="adicionaraocarrinho"),
    path('removerdocarrinho/', views.RemoverCarrinho.as_view(), name="removerdocarrinho"),
    path('carrinho/', views.Carrinho.as_view(), name="carrinho"),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name="resumodacompra"),
    path('tabela/', views.Tabela.as_view(), name="tabela"),
    path('variacoes/', views.Variacoes_json.as_view(), name="variacoes"),
    path('busca/', views.Busca.as_view(), name="busca"),
    path('entrada/', views.EntradaProduto.as_view(), name="entrada")
]

produto/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from datetime import datetime
from PIL import Image
from django.utils import timezone
from django.utils.text import slugify 
import os

class Produto(models.Model):
    nome = models.CharField(max_length=200)
    descricao = models.TextField(max_length=255)
    descricao_longa = models.TextField()
    imagem = models.ImageField(upload_to='produto_imagens/%Y/%m/', blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    preco_marketing = models.FloatField()
    preco_marketing_promocional = models.FloatField(default=0)
    tipo = models.CharField(
        default='V', 
        max_length=1, 
        choices=(
            ('V', 'Variável'), 
            ('S', 'Simples'),
        )
    )

    @staticmethod
    def resize(img, new_width=800):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size

        if original_width <= new_width:
            print('Retornando, largura original menor que nova largura')
            img_pil.close()
            return
        
        new_height = round((new_width - original_height) / original_width) 

        new_img = img_pil.resize((new_width, new_height), Image.LANCZOS)
        new_img.save(
            img_full_path,
            optimize=True,
            quality=50
        )   


    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.nome)}-{self.pk}'
            self.slug = slug

        super().save(*args, **kwargs)


    def __str__(self):
        return self.nome   

class ProdutoSimples(models.Model):
    nome_produto = models.CharField(max_length=100)
    nome_variacao = models.CharField(max_length=100)
    preco = models.FloatField(default=0)
    preco_promocional = models.FloatField(default=0)  
    quantidade = models.FloatField(default=0)
    estoque = models.IntegerField()

    class Meta:
        managed = False 

class Variacao(models.Model):
    
    nome = models.CharField(max_length=255, blank=True, null=True)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    preco = models.FloatField(default=0)
    preco_promocional = models.FloatField(default=0)
    estoque = models.PositiveBigIntegerField(default=1)
    id_preco_stripe = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.produto.nome + '  -  ' + self.nome

    class Meta:
        verbose_name = 'Variação'
        verbose_name_plural = 'variações'        

class SessaoCarrinho(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    Variacao = models.ForeignKey(Variacao, on_delete=models.CASCADE, null=False)
    quantidade = models.PositiveIntegerField(null=False)
    preco_quantitativo = models.FloatField()
    preco_quantitativo_promocional = models.FloatField()
    slug = models.TextField(null=True)

    class Meta:
        verbose_name = "Carrinho da sessão salva"
        db_table = "sessao_carrinho"   

class EntradaProduto(models.Model):
    variacao = models.ForeignKey(Variacao, on_delete=models.CASCADE, null=False)
    quantidade = models.PositiveIntegerField(null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    preco_final = models.FloatField()
    data = models.DateField(default=datetime.now().date())
    hora = models.TimeField(default=timezone.now().time())
    desativado = models.BooleanField(default=False)

class SaidaProduto(models.Model):
    variacao = models.ForeignKey(Variacao, on_delete=models.CASCADE, null=False)
    quantidade = models.PositiveIntegerField(null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    preco_final = models.FloatField()
    data = models.DateField(default=datetime.now().date())
    hora = models.TimeField(default=timezone.now().time())
    desativado = models.BooleanField(default=False)
    pedido = models.ForeignKey('pedido.Pedido', on_delete=models.CASCADE)

produto/views.py
from django.shortcuts import render, get_list_or_404, reverse, redirect, get_object_or_404
from django.core import serializers
from django.core.paginator import Paginator
from django.views.generic.list import ListView
from django.views import View
from django.views.generic.detail import DetailView
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.db.models import Q, Count, QuerySet
from produto.models import Produto, Variacao 
from produto.produto_service import ProdutoService
from perfil.models import PerfilUsuario
from pedido.models import ItemPedido
import json
import requests

class DispachProdutosMaisVendidos(View):

    def dispatch(self, *args, **kwargs):
        self.produtos_mais_vendidos = ProdutoService().get_produtos_mais_vendidos()
        return super().dispatch(*args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['produtos_mais_vendidos'] = self.produtos_mais_vendidos     
        return context
    
class ListaProdutos(DispachProdutosMaisVendidos, ListView):    
    model = Produto
    template_name = 'produto/lista.html' 
    context_object_name = 'produtos'
    paginate_by = 6


class DetalheProduto(DispachProdutosMaisVendidos, DetailView):
    model = Produto
    template_name = 'produto/detalhe.html' 
    context_object_name = 'produto'
    slug_url_kwarg = 'slug'

class AdicionarCarrinho(View):
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get('HTTP_REFERER', reverse('produto:lista'))
        variacao_id = self.request.GET.get('vid')
        qtd_form_param = self.request.GET.get('quantidade')
        
        if not variacao_id:
            messages.error(
                self.request,
                'Produto não existe'
            )
            return redirect(http_referer)
        
        variacao = get_object_or_404(Variacao, id=variacao_id)
        variacao_estoque = variacao.estoque
        produto = variacao.produto
        
        produto_id = produto.id
        produto_nome = produto.nome
        variacao_nome = variacao.nome or ''
        preco_unitario = variacao.preco
        preco_unitario_promocional = variacao.preco_promocional
        quantidade = qtd_form_param if qtd_form_param is not None else 1 
        slug = produto.slug
        imagem = json.dumps(str(produto.imagem))
        
        if variacao.estoque < 1:
            messages.error(
                self.request,
                'Estoque insuficiente'
            )
            return redirect(http_referer)
        
        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}
            self.request.session.save()
            
        carrinho = self.request.session['carrinho']
        
        if variacao_id in carrinho:
            quantidade_carrinho = float(carrinho[variacao_id]['quantidade'])
            #TODO: pegar quantidade dinamicamente
            quantidade_carrinho += float(quantidade)
            
            if variacao_estoque < int(quantidade_carrinho):
                messages.error(
                    self.request,
                    f'Estoque insuficiente para {quantidade_carrinho}x no produto {produto_nome}.' 
                    f'Adicionamos {variacao_estoque}x no seu carrinho'
                )
                quantidade_carrinho = variacao_estoque
            
            carrinho[variacao_id]['quantidade'] = quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo'] = preco_unitario * quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo_promocional'] = preco_unitario_promocional * quantidade_carrinho  
        else:
            carrinho[variacao_id] = {
                'produto_id' : produto_id,
                'produto_nome' : produto_nome,
                'variacao_nome' : variacao_nome,
                'variacao_id' : variacao_id,
                'preco_unitario' : preco_unitario,
                'preco_unitario_promocional' : preco_unitario_promocional,
                'quantidade' : quantidade,
                'slug' : slug,
                'preco_quantitativo_promocional': preco_unitario_promocional * int(quantidade),
                'preco_quantitativo' : preco_unitario * int(quantidade),
                'imagem' : imagem
            }

        ProdutoService().insert_item_session_carrinho(carrinho[variacao_id], self.request.user)

        self.request.session.save()  

        messages.success(
            self.request,
            f'Produto {produto_nome} {variacao_nome} adicionado no seu carrinho'
        )
        
        return redirect('produto:carrinho')

class RemoverCarrinho(View):
    
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('produto:lista')
        )
        variacao_id = self.request.GET.get('vid')
        
        if not variacao_id:
            return redirect(http_referer)
        
        if not self.request.session.get('carrinho'):
            return redirect(http_referer)
        
        if variacao_id not in self.request.session['carrinho']:
            return redirect(http_referer)
        
        carrinho = self.request.session['carrinho'][variacao_id]
        
        messages.success(
            self.request,
            f'Produto {carrinho["produto_nome"]} {carrinho["variacao_nome"]} removido do seu carrinho'
        )
        del self.request.session['carrinho'][variacao_id]
        
        variacao = Variacao.objects.filter(id=variacao_id).first()
        ProdutoService().delete_item_session_carrinho(self.request.user, variacao)
        
        self.request.session.save()
        
        return redirect(http_referer)

class Carrinho(DispachProdutosMaisVendidos, View):
    #TODO: salvar os itens da sessao quando carrega o carrinho
    
    def get(self, *args, **kwargs):
        context = {
            'carrinho': self.request.session.get('carrinho'),
            'produtos_mais_vendidos': self.produtos_mais_vendidos
        }
        return render(self.request, 'produto/carrinho.html', context)

class ResumoDaCompra(View):
    
    #verificar validate do token, transferir para arquivo
    bearer_token = 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZWU4OWMyMmE1ZTIyNjlmNWQyOTA1MzJiMzVjYzY2ZjMyY2FlMDIyZDM1OGEwMDFmMTNhZGViZTNjN2VjYzBmY2IxNDM1NzAzMDI4MjgxMTMiLCJpYXQiOjE3MTkwMTAzMTIuOTA1NjI3LCJuYmYiOjE3MTkwMTAzMTIuOTA1NjI5LCJleHAiOjE3NTA1NDYzMTIuODkxMDIzLCJzdWIiOiI5YzU3YzA5NS0wZTVhLTRmODEtYjlhOC0yYmM4ZTAzZDI4NzciLCJzY29wZXMiOlsic2hpcHBpbmctY2FsY3VsYXRlIiwiZWNvbW1lcmNlLXNoaXBwaW5nIl19.ZlVxabpqdJe8K_PYL9bo0MaElGo9YwxCCCEaPsA5GLOW_q82syoirhkLUsHg82DZUvLVeJH5W8jGAWyqAp8VxOc22YL-3rLLKiFTLQvsapO1vS9j6C9YXXQx0PXzkvBIknIri--1L5lpaRR9nPj3bp_OQULIOsnYkzI2aJ8H8OQ5XA3HT-b7lEqMOoyrpZbHGNtHXaOYL0NWyFb9Bft2Nbez10oRy5uEPm9svUj6RruLjbRMFIIBkGkdqjpSMtcAwCJCQm8OyDgdLxA16YseXkx6Gc32FkiuB_gaORxw_LckOIgO6z4f15PMkytB_MGsHDT7sIv6pXyd9d11qu_aXjHEXxcWuJ_4QszDmKnfXRQ8JJ4JYmw6F2W18sJSynuaSId2te8Sh3gBIkb-wCUC2e89uYXf33eI40SZ0cIgIHqJ4xd11qWtS-I7TzdDjWWPOILf2wdRwXNwiHr5QVsBIm0eoqmud65I9ttIKL9JTQ_JlT0E0f-4iLV392_LabJ8R9ikQq03AC5JwlhEcg3fogIITWLs3K6MNlxcPooVpSmr97u-1fmuDk_naE2mzCwS_4nI8N3QyufO4q-Vzfi6xEYsvsVhtyufU0sJRq3X9DgwJtupip2VGwmfoLoXmrAEXnCNKwdfdNj9T1ePzVMkWSWWM2wnYsrpLbQLkpNVIOg'
    
    def get_lista_frete_melhorenvio(self, perfil):
        
        url = 'https://melhorenvio.com.br/api/v2/me/shipment/calculate'
        
        perfil = PerfilUsuario.objects.filter(usuario=self.request.user).first()    
        data = {
            "from" : {
                "postal_code": "18910066",
            },
            "to" : {
              "postal_code" : perfil.cep,  
            }, 
            "package": {
                "height": 4,
                "width": 12,
                "length": 17,
                "weight": 0.3
            }    
        }
        headers = { 
                    "Authorization" :  self.bearer_token,
                    "Content-Type" : "Application/json",
                    "Accept" : "Application/json"
                  }
        try:
            response = requests.post(url, headers=headers, json=data)
            return response.json()
        except Exception as error:
            print(error)
    
    def get(self, *args, **kwargs):
        
        if not self.request.user.is_authenticated:
            return redirect('perfil:criar')
        
        perfil = PerfilUsuario.objects.filter(usuario=self.request.user).first()
        if perfil is None:
            messages.error(self.request, 'Usuario sem perfil')
            return redirect('perfil:criar')
        
        if not self.request.session.get('carrinho'):
            messages.error(
                self.request,
                'Carrinho vazio'
            )
            return redirect('produto:lista')
        
        fretes = self.get_lista_frete_melhorenvio(perfil)                       
        
        contexto = {
            'usuario': self.request.user,
            'carrinho': self.request.session['carrinho'],
            'perfil': perfil,
            'fretes': fretes,
            'produtos_mais_vendidos': ProdutoService().get_produtos_mais_vendidos()
        }
        return render(self.request, 'produto/resumodacompra.html', contexto)


class Tabela(ListView):
    model = Produto
    template_name = 'produto/tabela.html'
    context_object_name = 'produtos'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['area_sem_produtos'] = True
        return context

class EntradaProduto(View):
    
    def get(self, *args, **kwargs):
        
        context = {
            'area_sem_produtos' : True,  
            'variacoes' : Variacao.objects.select_related('produto')
        }

        return render(self.request, 'produto/entrada.html', context)
    

produto/templates/produto/carrinho.html
{% extends 'base.html' %}

{% load omfilters %}

{% load static %}

{% block conteudo %}

<div class="row mt-3">
    <div class="col">
        <h3>Carrinho de compras</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

        <div class="table-responsive">
            <table class="table">
                <tr>
                    <th class="d-none d-lg-block">Imagem</th>
                    <th>Nome e variação</th>
                    <th></th>
                    <th class="text-center">Quantidade</th>
                    <th class="text-center">Total</th>
                </tr>

                {% if carrinho.values %}                 
                    {% for item in carrinho.values %}
                        <tr>
                            <td class="d-none d-lg-block">
                                {% if item.imagem %}
                                    <img class="cart-img" src={% get_media_prefix %}{{item.imagem|remove_aspas}}>
                                {% endif %}    
                            </td>
                            <td>
                                <a href="{% url 'produto:detalhe' item.slug %}">
                                {{ item.produto_nome }} - {{ item.variacao_nome }}
                                </a>
                            <td>                       
                            <td class="text-center">{{ item.quantidade }}</td>                        
                            <td class="text-right">
                                {% if item.preco_quantitativo_promocional %}
                                    R$  {{ item.preco_quantitativo_promocional }}
                                {% else %}
                                    R$  {{ item.preco_quantitativo }}
                                {% endif %}    
                                <a class="ml-3" href="{% url 'produto:removerdocarrinho' %}?vid={{item.variacao_id}}">
                                    <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                                </a>
                            </td> 
                        </tr>
                    {% endfor %}
                                    
                {% else %}
                    <tr>
                        <td colspan="5" class="text-center">
                            <h4>Seu carrinho está vazio,</h4>
                            <p>comece por <a href="{% url 'produto:lista' %}"> aqui</a></p>
                        </td>
                    </tr>   
                {% endif %}        
            </table>
        </div>
    </div>
</div>

{% if carrinho.values %}
    <div class="row mt-3">
        <div class="col-lg">
            <p class='lead'>Total no carrinho</p>

            <div class='table-responsive'>
                <table class="table">
                    <tr>
                        <td class="text-right">
                        {% if request.session.carrinho %}  
                            <p class="lead">
                            {{request.session.carrinho|cart_total_preco|formata_preco}}
                            </p>
                        {% endif %}
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="col-lg mt-auto bottom_40pixel">
            <a class="btn btn-lg btn-block btn-primary" href="{% url 'produto:lista' %}">
                Continuar comprando
            </a>    
        </div>    
        <div class="col-lg mt-auto bottom_40pixel">
            {% if request.user.is_authenticated %}
            <a class="btn btn-lg btn-block btn-primary" href="{% url 'produto:resumodacompra' %}">
                Finalizar compra
            </a>
            {% else %}
            <a class="btn btn-lg btn-block btn-primary" href="{% url 'perfil:criar' %}">
                Entrar com seu usuário
            </a>
            {% endif %}
        </div>
    </div>
{% endif %}

{% endblock %}

produto/templates/produto/detalhe.html
{% extends 'base.html' %}

{% load omfilters %}

{% block conteudo %}

<div class="row">
    <div class="col-lg">
        <div class="row no-gutters">
            <div class="col-lg-12">
                {% if produto.imagem %}
                    <img class="img-fluid" src="{{ produto.imagem.url }}">
                {% endif %}    
            </div>
        </div>
    </div>
    <div class="col-lg">
        <div class="mt-4 mt-lg-0">
            <h1 class="h2">{{produto.nome}}</h1>
            <p class="lead">{{produto.descricao}}</p>
            <p class="lead">
                {% if produto.preco_marketing_promocional %}
                    <span id="variation-preco-promocional" 
                          class="lead product-price">
                          {{produto.preco_marketing_promocional|formata_preco}}
                    </span>
                    <span id="variation-preco"
                          class="lead product-old-price text-muted">
                          {{produto.preco_marketing|formata_preco}}
                    </span>
                {% else %}
                    <span id="variation-preco-normal" 
                    class="lead product-price">{{produto.preco_marketing|formata_preco}}</span>
                {% endif %}          
            </p>

            <form action="{% url 'produto:adicionaraocarrinho' %}" id="form-add-to-cart">
                {% if produto.variacao_set %}
                    <div class="form-group">
                        <input type="number" id="quantidade" name="quantidade" value="1" 
                            class="form-control form-control-lg input_qtd">
                        <select id="select-variacoes" name="vid" 
                        class="form-control form-control-lg input_variacao">
                            {% for variacao in produto.variacao_set.all %}
                                {% if variacao.preco_promocional %}
                                    <option data-preco="{{variacao.preco|formata_preco}}" 
                                            data-preco-promocional="{{variacao.preco_promocional}}" 
                                            value="{{variacao.id}}">
                                        {% if variacao.nome %}
                                            {{variacao.nome}}
                                        {% else %}
                                            {{variacao}}
                                        {% endif %}    
                                    </option>
                                {% else %}
                                    <option data-preco="{{variacao.preco|formata_preco}}" 
                                            value="{{variacao.id}}">
                                        {% if variacao.nome %}
                                            {{variacao.nome}}
                                        {% else %}
                                            {{variacao}}
                                        {% endif %}
                                    </option>
                                {% endif %}    
                            {% endfor %}
                        </select>
                    </div>
                {% endif %}    
                <div class="btn-add-cart">
                    <button type="submit" class="btn btn-primary btn-lg btn-block">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        Adicionar ao carrinho
                    </button>
                </div>

            </form>


        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="mt-5 mb-5">
            <h2 class="text-center">{{produto.nome}}</h2>
            {{produto.descricao_longa | linebreaks}}
        </div>
    </div>
</div>

{% endblock %}

produto/templates/produto/entrada.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% load omfilters %}

{% block conteudo %}

<script>
    $(document).ready(function(){
        
        $.noConflict();

        const table = $('#table_id').DataTable({
            colReorder: true,
            keys: true,
        });

        $(".dt-layout-cell").first().hide()
        $("#dt-search-0").css('width','90%');
        $(".card-body").css('padding','0.75rem');

        table.on('click', 'td', function (e) {
            row = $(this).parent('tr');
            nomeproduto_selecionado = row.children('td.nome_produto').html();
            nomevariacao_selecionado = row.children('td.nome_variacao').html();
            $("#id_variacao").val(row.attr('variacao_id'));
            $('#preco_atual').val(row.children('td.preco_final').html());
            $('#nome_produto_variacao').html(nomeproduto_selecionado + ' - ' + nomevariacao_selecionado);
        });  

    } );  
</script>

<div class="container d-flex vh-100"> 

    <div class="card borderless">
        <h3>Cadastro de entrada de mercadoria</h3>
        <p class="mt-4">Em caso de erro ao cadastrar a entrada utilize a saida de mercadorias:</p>
        <div class="card-body">
           
            <table id="table_id" class="display">
                <thead>
                    <tr>
                        <th>nome do produto</th>
                        <th>nome da variação</th>
                        <th>Preço</th>
                        <th>Preço promocional</th>
                    </tr>
                </thead>
                <tbody>
                    {% for variacao in variacoes %}
                    <tr variacao_id="{{variacao.id}}">
                        <td class="nome_produto">{{variacao.produto.nome}}</td>             
                        <td class="nome_variacao">{{variacao.nome}}</td>                       
                        <td class="preco_final">{{variacao.preco|formata_preco}}</td>
                        <td>{{variacao.preco_promocional|formata_preco}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table> 

        </div>
        <div class="card-body">
            
            <form method="POST" action="{% url 'produto:entrada' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="produto">Produto</label>
                    <h6 id="nome_produto_variacao"></h6>
                </div>
                <div class="form-group">
                    <label for="quantidade">Quantidade</label>
                    <input type="text" name="quantidade" id="quantidade" 
                            placeholder="" class="form-control input-number">
                </div>
                <div class="form-group">
                    <label for="InputUsuario">Preço Atual</label>
                    <input type="text" name="preco_atual" 
                            class="form-control input-number" id="preco_atual">
                </div>
                <input type="hidden" name="id_variacao" id="id_variacao"/>
                <button type="submit" id="btn_login_perfil" 
                        class="btn btn-primary btn-block btn-lg btn_login">
                    Cadastrar
                </button>  
            </form> 
        </div>
         

    </div>

</div>
{% endblock %}

produto/templates/produto/lista.html
{% extends 'base.html' %}

{% load omfilters %}

{% load static %}

{% block conteudo %}
<div class="row">
    <div class="col-lg-12">
        <div class="card-columns">

            {% for produto in produtos %}   
            
            <div class="card">
                {% if produto.imagem %}
                  <a href="{% url 'produto:detalhe'  produto.slug %}">  
                    <img class="card-img-top" src="{{ produto.imagem.url }}" alt="Card image cap">
                  </a>
                {% endif %} 

                <div class="card-body">
                    <h5 class="card-title">{{ produto.nome }}</h5>
                    <p class="card-text">{{ produto.descricao }}</p>
                    <div class="container product-price-block text-center">
                        {% if produto.preco_marketing_promocional > 0 %}
                            <span class="product-price">
                                {{ produto.preco_marketing_promocional|formata_preco }}
                            </span>
                        {% endif %}
                            <span class="product-old-price text-muted">
                                {{ produto.preco_marketing|formata_preco }}
                            </span>
                    </div>
                </div>
                <div class="card-footer bg-transparent border-top-light-custom text-center">
                    <a href="{% url 'produto:detalhe'  produto.slug %}" class="btn btn-primary btn-sm m-1 btn-block">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        Comprar
                    </a>
                </div>
            </div>
            {% endfor  %}

        </div>
    </div>
</div>

<div class="row mt-3">
    <div class="col">
        {% include 'parciais/_pagination.html' %}
    </div>
</div>

{% endblock conteudo %}